Added basic alien browser
wildj79/foundryvtt-starfinder pull request #344
Opened 2021-03-28 18:45 UTC by rrenna

As per user request, I've added a (very basic) alien browser.

![image](https://user-images.githubusercontent.com/849462/112763870-46499c00-8fd4-11eb-9a19-10b7e0d690ce.png)

![image](https://user-images.githubusercontent.com/849462/112763813-0da9c280-8fd4-11eb-961e-08098caad124.png)

Sort by name or CR.
Filter by size.
CRs which are 1/3 or 1/2 have special display logic.

![image](https://user-images.githubusercontent.com/849462/112763849-329e3580-8fd4-11eb-8a55-dda0052e8d35.png)

2021-03-31 13:22 UTC, rrenna commented
I've added a type filter.

2021-04-26 15:18 UTC, wildj79 requested changes
As in a previous PR, just some little nitpicky issues. 

But, I'm not sure what's going on with `src/module/packs/item-browser.js`. It looks like it's just a reorganization and whitespace normalization of the code, but it's kind of hard to read. I would prefer if these types of refactors were done inside of there own PR's. If there were changes beyond code cleanup, I can't tell.

2021-04-26 15:18 UTC, wildj79 commented on src/module/packs/alien-archive-browser.js
> +                if (item.data.details.cr == (1/3)) {
You should prefer `===` over `==`.

2021-04-26 15:18 UTC, wildj79 commented on src/module/packs/alien-archive-browser.js
> +                else if (item.data.details.cr == (1/2)) {
You should prefer `===` over `==`.

2021-04-26 15:18 UTC, wildj79 commented on src/module/packs/alien-archive-browser.js
> +        if (aVal == bVal) {
You should prefer `===` over `==`.

2021-04-27 07:54 UTC, TimToxopeus commented
> But, I'm not sure what's going on with `src/module/packs/item-browser.js`. It looks like it's just a reorganization and whitespace normalization of the code, but it's kind of hard to read. I would prefer if these types of refactors were done inside of there own PR's. If there were changes beyond code cleanup, I can't tell.

I believe there are also some edits to support returning actors instead of just items. I also prefer if it was done separate from newline changes because now it is hard to diff in github. I actually had to pull it in and kdiff3 it with whitespace disabled.

@rrenna and I had a brief chat about it, and I think we should rename item browser to entity browser, to properly reflect the fact it no longer just returns items.

2021-05-01 09:49 UTC, TimToxopeus commented
I'm going to request holding off on this one until after we have 0.8 working. Changes have to be made to the item browser for 0.8 compat, and since this isn't merged or processed still, I would wait with merging.

2021-05-01 12:20 UTC, rrenna commented
Sounds good. I also need to confirm the changes in the parent class was just tab space normalization. So I have that feedback to address before we can merge anyways.

2021-05-12 18:57 UTC, wildj79 commented
I'm going to change this one to a draft for now. We'll have to revisit this one after v0.8.x hits stable.

2021-10-02 10:54 UTC, TimToxopeus commented
@rrenna Any chances you are possibly going to do anything here, we've been v0.8 stable for a while now, and there was some work still to be done here I think. Particularly with the refactoring of the way the document browser base class was put together, so it better reflects both items and actors.

2022-01-09 13:25 UTC, merged