Migrate container item jsons as to not trip migration
wildj79/foundryvtt-starfinder pull request #616
Opened 2022-05-12 01:04 UTC by LebombJames

At the moment, a container migration trips if a container has any of the properties listed on line 955 of `actor-inventory-utils.js`, however, the container items in the compendium have some of those very properties, so I've removed them. 

The migration itself is still a bit problematic, as it doesn't work correctly if the items only have _some_ of the properties [see above 😉], and I may try to rectify that, but at least by changing the compendium JSONs the problem is no longer propagating.

2022-05-12 17:43 UTC, LebombJames commented
Ok, at this point:

- Container items in the compendium have been migrated
- When a migration is performed on a container with *some* old values, if it has new values, those will be retained.
- However, the migration seems to be triggering every world boot because it doesn't remove the old values... and I can't figure out why it doesn't.

2022-05-15 02:52 UTC, wildj79 requested changes
The `json` changes look good, but I'm not sure what you're trying to do in `actor-inventory-utils.js`. I think it might be better in this case to remove those changes from this PR and issue a new one for them, that way we can get the compendium changes in a release in the next day or two.

2022-05-15 12:58 UTC, LebombJames commented
Got it, will do.

2022-05-15 14:59 UTC, wildj79 commented
Mergin'

2022-05-15 15:00 UTC, merged